name: Release AWS X-Ray Remote Sampler for OpenTeletry Go
on:
  workflow_dispatch:
    inputs:
      xray-remote-sampler-version:
        description: The version to tag the release with, e.g., 1.2.0
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
            go-version: "1.24.0"
            check-latest: true

      - name: Ensure Unit Tests are passing
        run: |
          cd samplers/aws/xray
          go test ./...

      # TODO: Uncomment when we make the first release
      # - name: Tag AWS X-Ray Remote Sampler module
      #   run: |
      #     git tag samplers/aws/xray/v${{ inputs.udp-exporter-version }}

      # - name: Publish tag for AWS X-Ray Remote Sampler module
      #   run: git push --tags